export { default as Header } from './Header'
export { default as Main } from './Main'
export { default as Controls } from './Controls'
export { default as TotalPrice } from './TotalPrice'
export { default as MyModal } from './MyModal'